### ISSUE TITLE
Daemon mode fails when there is no stdin

### ISSUE THREAD

**Issue by X-dark** [axujen/mpdrandom#12]
If launched in daemon, as a Systemd Unit, there is no stdin. In that situation, it fails with the following error:

```
Exception in callback Queue.put_nowait('received line on stdin')
handle: <Handle Queue.put_nowait('received line on stdin')>
Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.9/asyncio/queues.py", line 151, in put_nowait
    raise QueueFull
asyncio.queues.QueueFull
```
I got a similar error when running manually with `mpdrandom < /dev/null`

Could you maybe add an option to not wait for STDIN in daemon mode?

**Comment by axujen** [comment]
i think this maybe caused by https://github.com/axujen/mpdrandom/pull/11/commits/cc7fb542f54fee53dee28b72feb3cebd23c05f13
i will look into it, maybe @cbumae can help aswell

EDIT:
mpdrandom < /dev/null produces no errors on my end, its mpdrandom -d < /dev/null that produces the error which is to be expected

Anyway i think ill either have to make some exception in idleloop() for when theres no stdin, or make a new daemon mode argument that doesn't require stdin for systemd

stdio_monitor_thread() also seems like a good place to check for stdin before running the loop, i will check on this tomorrow after work
